### ISSUE TITLE
Invalid time value - NL Stations (2.1.5)

### ISSUE THREAD

**Issue by TangoFanta** [Forceh91/retro-env-can-weather-chan#875]
Hi Everyone,

After fresh install of node (20.18.1) and yarn (1.22.22) I installed 2.1.5. Still getting "invalid time value" for Newfoundland weather stations and no display on simulator screen. Is there anything I'm missing? I've installed on Antix 23.2 and Zorin 17.2 with same result.

Here is the error in the yarn log:

ECCC API RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at CurrentConditions.generateWeatherStationTimeData (/home/me/apps/v2.1.5-50e9e54-node-20.x/src/lib/eccc/conditions.ts:213:35)
    at <anonymous> (/home/me/apps/v2.1.5-50e9e54-node-20.x/src/lib/eccc/conditions.ts:142:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

thanks
-

**Comment by Forceh91** [comment]
Hmm I wonder if ECCC are passing a timezone that the date library doesn't know about. What timezone would NL be on? I thought it'd be EST but I guess not?

**Comment by TangoFanta** [comment]
I would assume they're using NST (Newfoundland Standard Time). That is EST+1h30, UTC-2h30m(dst), UTC-3h30m (non-dst). I tried weather stations in Labrador that use AST and they seem to work fine. So either the timezone itself is an issue, or the extra 30min offset possibly?

**Comment by Forceh91** [comment]
Ah yeah it might not be picking up NST. I had to manually account for AST. Seems I need to do the same for NST then.

**Comment by TangoFanta** [comment]
Ughhh. Us and our extra 30 mins. Not the first time it has created problems.

Thanks so much for creating this. Nice to know I'm not the only one that likes this type of thing. Can't wait to set this up in the house on the modulator.

**Comment by Forceh91** [comment]
Ah I just took a quick look at this and I accounted for NDT but not NST heh. Whoops.

Would you be able to give this branch a go and see if that fixes it? `fix/date-not-handling-nst-timezone` (#884)

**Comment by TangoFanta** [comment]
Ugh. Sorry I didn't try that myself. I was thinking it was too obvious. The extra "date.replace" thing works great I think, although to avoid revising again next spring, I would change the line to the one below (or similar) so it accounts for AST/ADT as well.

const fixedTimezone = date.replace("AST", "GMT-0400").replace("ADT", GMT-0300").replace("NST", "GMT-0330").replace("NDT", "GMT-0230");

Also, just in case this is related to the timezone, I am getting errors when trying to fetch Climate Normals. I assume it's coming from the sax module and being passed on to the other modules? Or does this just mean the station doesn't have Climate Normal info? I've checked on the ECC site and it does list data, unless the formatting has changed.

[2024-12-06 19:28:12] [CLIMATE_NORMALS] Failed to fetch historical normals <ref *1> Error: Unmatched closing tag: element
Line: 19
Column: 10
Char: >
    at error (/home/user/apps/v2.1.6-47d6025-node-21.x/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/home/user/apps/v2.1.6-47d6025-node-21.x/node_modules/sax/lib/sax.js:677:7)
    at closeTag (/home/user/apps/v2.1.6-47d6025-node-21.x/node_modules/sax/lib/sax.js:879:7)
    at SAXParser.write (/home/user/apps/v2.1.6-47d6025-node-21.x/node_modules/sax/lib/sax.js:1436:13)
    at module.exports (/home/user/apps/v2.1.6-47d6025-node-21.x/node_modules/xml-js/lib/xml2js.js:346:12)
    at <anonymous> (/home/user/apps/v2.1.6-47d6025-node-21.x/src/lib/eccc/climateNormals.ts:49:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  note: [Circular *1]
}

Cheers

**Comment by Forceh91** [comment]
Ah great!

That's not a module I've installed myself so must be something else doing it. I suspect judging by `<ref *1> Error: Unmatched closing tag: element
Line: 19
Column: 10
Char: >` that you've not got the right climate normals data entered. Sometimes stations just generally don't have that data available for whatever reason. If it's in the spreadsheet thats linked on the config page and the ECCC historical page it should work though..
